/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import calculated.Sumup;
import controlers.MainWindowsControler;
import db.entities.Discounts;
import db.entities.Products;
import exceptions.ProcessingException;
import java.awt.image.BufferedImage;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Miro
 */
public class MainWindow extends CommonWindow {

    private JFileChooser fileChooser = new JFileChooser();
    private JFileChooser directoryChooser;
    private MainWindowsControler controler;
    
    public MainWindow() throws Exception {
        extendedInitComponents();
        controler = new MainWindowsControler(this);
        repaintsumupsTable();
    }

    private void extendedInitComponents(){
        initComponents();
        sumups = new ArrayList<Sumup>();
        directoryChooser = new JFileChooser();
        directoryChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jMenuItem1 = new javax.swing.JMenuItem();
        PromotionCheckerPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("PromotionCheckerPU").createEntityManager();
        discountsQuery = java.beans.Beans.isDesignTime() ? null : PromotionCheckerPUEntityManager.createQuery("SELECT d FROM Discounts d order by d.name");
        discountsList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(discountsQuery.getResultList());
        productsQuery = java.beans.Beans.isDesignTime() ? null : PromotionCheckerPUEntityManager.createQuery("SELECT w FROM Products w order by w.name");
        productsList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(productsQuery.getResultList());
        mainTable = new javax.swing.JTabbedPane();
        productPanel = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        discountPanel = new javax.swing.JScrollPane();
        discountTable = new javax.swing.JTable();
        sumupPanel = new javax.swing.JScrollPane();
        sumupTable = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        readProducts = new javax.swing.JMenuItem();
        readDiscounts = new javax.swing.JMenuItem();
        saveSumup = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        saveSampleFiles = new javax.swing.JMenu();
        saveSampleDiscounts = new javax.swing.JMenuItem();
        saveSampleProducts = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");
        jMenuItem1.setName("jMenuItem1"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Promotion checker");
        setName("Form"); // NOI18N

        mainTable.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        mainTable.setName("mainTable"); // NOI18N

        productPanel.setName("productPanel"); // NOI18N

        productTable.setColumnSelectionAllowed(true);
        productTable.setName("productTable"); // NOI18N

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, productsList, productTable);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${name}"));
        columnBinding.setColumnName("Name");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${price}"));
        columnBinding.setColumnName("Price");
        columnBinding.setColumnClass(Double.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${amount}"));
        columnBinding.setColumnName("Amount");
        columnBinding.setColumnClass(Integer.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        productPanel.setViewportView(productTable);
        productTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        mainTable.addTab("Stan magazynu", productPanel);

        discountPanel.setName("discountPanel"); // NOI18N

        discountTable.setName("discountTable"); // NOI18N

        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, discountsList, discountTable);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${name}"));
        columnBinding.setColumnName("Nazwa");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${amountinpercentage}"));
        columnBinding.setColumnName("%");
        columnBinding.setColumnClass(Double.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        discountPanel.setViewportView(discountTable);

        mainTable.addTab("Rabaty", discountPanel);

        sumupPanel.setName("sumupPanel"); // NOI18N

        sumupTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nazwa", "Cena ", "Rabat %", "Rabat PLN", "Cena po rabacie"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sumupTable.setName("sumupTable"); // NOI18N
        sumupPanel.setViewportView(sumupTable);

        mainTable.addTab("Ceny z uwzględnieniem rabatów", sumupPanel);

        jMenuBar1.setName("jMenuBar1"); // NOI18N

        jMenu1.setText("Plik");
        jMenu1.setName("jMenu1"); // NOI18N

        jMenu3.setText("Wczytaj");
        jMenu3.setName("jMenu3"); // NOI18N

        readProducts.setText("Stan magazynu");
        readProducts.setName("readProducts"); // NOI18N
        readProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readProductsActionPerformed(evt);
            }
        });
        jMenu3.add(readProducts);

        readDiscounts.setText("Rabaty");
        readDiscounts.setName("readDiscounts"); // NOI18N
        readDiscounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readDiscountsActionPerformed(evt);
            }
        });
        jMenu3.add(readDiscounts);

        jMenu1.add(jMenu3);

        saveSumup.setText("Zapisz ceny po rabacie");
        saveSumup.setName("saveSumup"); // NOI18N
        saveSumup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveSumupActionPerformed(evt);
            }
        });
        jMenu1.add(saveSumup);

        jMenuBar1.add(jMenu1);

        helpMenu.setText("Pomoc");
        helpMenu.setName("helpMenu"); // NOI18N

        jMenuItem3.setText("Instrukcja");
        jMenuItem3.setName("jMenuItem3"); // NOI18N
        helpMenu.add(jMenuItem3);

        saveSampleFiles.setText("Zapisz przykładowy plik");
        saveSampleFiles.setName("saveSampleFiles"); // NOI18N

        saveSampleDiscounts.setText("Rabaty");
        saveSampleDiscounts.setName("saveSampleDiscounts"); // NOI18N
        saveSampleDiscounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveSampleDiscountsActionPerformed(evt);
            }
        });
        saveSampleFiles.add(saveSampleDiscounts);

        saveSampleProducts.setText("Stan magazynu");
        saveSampleProducts.setName("saveSampleProducts"); // NOI18N
        saveSampleProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveSampleProductsActionPerformed(evt);
            }
        });
        saveSampleFiles.add(saveSampleProducts);

        helpMenu.add(saveSampleFiles);

        jMenuItem4.setText("Informacje");
        jMenuItem4.setName("jMenuItem4"); // NOI18N
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        helpMenu.add(jMenuItem4);

        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTable, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTable, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void readDiscountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readDiscountsActionPerformed
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal != 0){
            return;
        }
        controler.readDiscountsFromXml(fileChooser.getSelectedFile());
    }//GEN-LAST:event_readDiscountsActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        JFrame infoView = new InfoWindow();
        infoView.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        infoView.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void saveSampleDiscountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveSampleDiscountsActionPerformed
        int returnVal = directoryChooser.showOpenDialog(this);
        if (returnVal != 0){
            return;
        }
        controler.saveDiscountFileExample(directoryChooser.getSelectedFile());
    }//GEN-LAST:event_saveSampleDiscountsActionPerformed

    private void saveSampleProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveSampleProductsActionPerformed
        int returnVal = directoryChooser.showOpenDialog(this);
        if (returnVal != 0){
            return;
        }
        controler.saveProductFileExample(directoryChooser.getSelectedFile());
    }//GEN-LAST:event_saveSampleProductsActionPerformed

    private void readProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readProductsActionPerformed
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal != 0){
            return;
        }
        controler.readProductFromXml(fileChooser.getSelectedFile());
    }//GEN-LAST:event_readProductsActionPerformed

    private void saveSumupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveSumupActionPerformed
        int returnVal = directoryChooser.showOpenDialog(this);
        if (returnVal != 0){
            return;
        }
        controler.saveSumupToXml(directoryChooser.getSelectedFile());
    }//GEN-LAST:event_saveSumupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    if (MainWindowsControler.expired()){
                        new ExpirationWindow().setVisible(true);
                    } else {
                        new MainWindow().setVisible(true);
                    }
                } catch (Exception ex) {
                    Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager PromotionCheckerPUEntityManager;
    private javax.swing.JScrollPane discountPanel;
    private javax.swing.JTable discountTable;
    private java.util.List<db.entities.Discounts> discountsList;
    private javax.persistence.Query discountsQuery;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JTabbedPane mainTable;
    private javax.swing.JScrollPane productPanel;
    private javax.swing.JTable productTable;
    private java.util.List<db.entities.Products> productsList;
    private javax.persistence.Query productsQuery;
    private javax.swing.JMenuItem readDiscounts;
    private javax.swing.JMenuItem readProducts;
    private javax.swing.JMenuItem saveSampleDiscounts;
    private javax.swing.JMenu saveSampleFiles;
    private javax.swing.JMenuItem saveSampleProducts;
    private javax.swing.JMenuItem saveSumup;
    private javax.swing.JScrollPane sumupPanel;
    private javax.swing.JTable sumupTable;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    private List<Sumup> sumups;
    
    public void repaintsumupsTable(){
        DefaultTableModel model = (DefaultTableModel) sumupTable.getModel();
        for (int i = 0; i < model.getRowCount(); ++i) {
            model.removeRow(i);
        }
        for (Sumup sumup : sumups){
            model.addRow(sumup.toArray());
        }
    }
    
    public void repiantProductTable(){
        productsList.clear();
        productsList.addAll(productsQuery.getResultList());
        productTable.repaint();
    }
    
    public void repaintDiscountsTable(){
        discountsList.clear();
        discountsList.addAll(discountsQuery.getResultList());
        discountTable.repaint();
    }
    
    public List<Products> getProductList(){
        return productsList;
    }
    
    public List<Discounts> getDiscountsList(){
        return discountsList;
    }
    
    public List<Sumup> getSumupList(){
        return sumups;
    }
    
    public void showCriticalError(String message){
        JOptionPane.showMessageDialog(this, "Nieznany błąd. \n" + message, "Błąd", JOptionPane.ERROR_MESSAGE);
    }
    
    public void showError(ProcessingException exception){
        switch(exception.getType()){
            case ProcessingException.MULTI_LINE :
                showError(exception.getErrorList());
                return;
            case ProcessingException.STRING_TYPE :
                showError(exception.getMessage());
        }
    }
    
    private void showError(List<String> list){
        String message = Arrays.toString(list.subList(0, list.size() > 10 ? 10 : list.size()).toArray());
        message = message.substring(1, message.length() - 1);
        if (list.size() > 10) {
            message += ", ...";
        }
        if (message.length() > 150){
            message = message.replaceAll(",", ", \n");
        }
        JOptionPane.showMessageDialog(this, "Błąd podczas wczytywania lini:\n" + message, "Wczytywanie nie powiodło się", JOptionPane.ERROR_MESSAGE);
    }
    
    private void showError(String message){
        JOptionPane.showMessageDialog(this, message, "Błąd podczas wczytywania pliku", JOptionPane.ERROR_MESSAGE);
    }
}
