DROP TABLE PRODUCTS;

create table PRODUCTS (ID INT not null primary key GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), 
        NAME VARCHAR(100),
        AMOUNT INT,
        PRICE DOUBLE,
        POSITION INT,
        CREATEDAT DATE
);

DROP TABLE DISCOUNTS;

create table DISCOUNTS (ID INT not null primary key GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), 
        NAME VARCHAR(100),
        AMOUNTINPERCENTAGE DOUBLE,
        CREATEDAT DATE
);